name: Beta Versioning

on:
  push:
    branches:
      - beta

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache NPM
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules/
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Install NPM
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: Compile with Gulp
        uses: elstudio/actions-js-build/build@v4
        with:
          args: buildAll --prod

      - name: Zip Files
        working-directory: ./
        run: zip -r ./system.zip ./dist/*

      # Get the most recent version number from the CHANGELOG.md file
      - name: Get Most Recent Version Number
        id: get-version
        run: echo "version=$(node ./.github/workflows/get-version.js)" >> $GITHuB_OUTPUT

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: .${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: true
          token: ${{secrets.GITHUB_TOKEN}}
          artifacts: "./system.zip, ./static/system.json"
          generateReleaseNotes: true
          tag: ${{ steps.get-version.outputs.version }}
