name: Automatic Versioning
on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Zip Files
        working-directory: ./
        run: zip -r ./system.zip ./*

      # Get the most recent version number from the CHANGELOG.md file
      - name: Get Most Recent Version Number
        id: get_version
        run: |
          version=$(grep -E '^##.*' CHANGELOG.md | head -n 1 | awk '{print $2}')
          echo "version=${version}" >> $GITHUB_OUTPUT
      
    # Substitute the Manifest and Download URLs in the module.json with the most recent version number
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: system.json
        env:
          version: ${{ steps.get_version.outputs.version }}
          manifest: https://github.com/sw5e-foundry/sw5e/releases/download/${{ steps.get_version.outputs.version }}/system.json
          download: https://github.com/sw5e-foundry/sw5e/releases/download/${{ steps.get_version.outputs.version }}/system.zip  
      
      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with: 
          allowUpdates: true
          name: .v${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          token: ${{secrets.GITHUB_TOKEN}}
          artifacts: './system.zip, ./system.json'
          generateReleaseNotes: true
          tag: ${{ steps.get-version.outputs.version }}
